spring:
  application:
    name: METER-DATA-MESSAGE-PRODUCER
  cloud:
    stream:
      bindings:
        output:
          destination: meter-data-message

server:
  port: 9195

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost