spring:
  application:
    name: TARIFF-REQUEST-PRODUCER
  cloud:
    stream:
      bindings:
        output:
          destination: tariff-message
      kafka:
        binder:
          zkNodes: zookeeper:2181
          brokers: kafka:9092

server:
  port: 9195

http:
  prefix: 'Prefix'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost